### ISSUE TITLE
add 3 terms to slim

### ISSUE THREAD

**Issue by sbello** [obophenotype/pro_obo_slim#46]
Please add these terms to the slim
peptide YY  - http://purl.obolibrary.org/obo/PR_000013526 
secretin - http://purl.obolibrary.org/obo/PR_000014543
resistin - http://purl.obolibrary.org/obo/PR_000013896

I need these to create eq for newly added MP terms.

Thanks,
Sue

**Comment by matentzn** [comment]
Best directly contact @rays22  on slack for help with this
